name: check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: macos-13
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # xcresultparser をインストール
      - run: brew tap a7ex/homebrew-formulae
      - run: brew install xcresultparser
      # 単体テスト実行 + カバレッジレポート出力
      - run: xcodebuild test -enableCodeCoverage YES -resultBundlePath artifacts/ResultBundle.xcresult -project TryTCA.xcodeproj -scheme TryTCA -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' build test
      # カバレッジレポートを xcresult 形式から XML 形式に変換
      - run: xcresultparser --output-format cobertura "artifacts/ResultBundle.xcresult" > "artifacts/coverage.xml"
      # Codecov にカバレッジレポートをアップロード
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
